"""added tags to news

Revision ID: af0b500c2f97
Revises: 
Create Date: 2025-10-21 18:40:10.272148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'af0b500c2f97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_news_author'), 'news', ['author'], unique=False)
    op.create_index(op.f('ix_news_image_url'), 'news', ['image_url'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=False)
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    op.create_index(op.f('ix_news_uid'), 'news', ['uid'], unique=False)
    op.create_table('pharmacists',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fellow', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('school_attended', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pcn_license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('induction_year', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('residential_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('place_of_work', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interest_groups', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_pharmacists_email'), 'pharmacists', ['email'], unique=True)
    op.create_index(op.f('ix_pharmacists_uid'), 'pharmacists', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacists_uid'), table_name='pharmacists')
    op.drop_index(op.f('ix_pharmacists_email'), table_name='pharmacists')
    op.drop_table('pharmacists')
    op.drop_index(op.f('ix_news_uid'), table_name='news')
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_image_url'), table_name='news')
    op.drop_index(op.f('ix_news_author'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
