"""added group to news

Revision ID: f389e07b7529
Revises: af0b500c2f97
Create Date: 2025-10-21 23:04:49.427881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f389e07b7529'
down_revision: Union[str, Sequence[str], None] = 'af0b500c2f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('news', sa.Column('group', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('news', sa.Column('group', sa.String(
        length=50), nullable=False, server_default='general'))
    op.create_index(op.f('ix_news_group'), 'news', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_group'), table_name='news')
    op.drop_column('news', 'group')
    # ### end Alembic commands ###
